name: pairx
channels:
  - conda-forge
dependencies:
  - fsspec
  - numpy
  - pip
  - python
  - pip:
    - captum==0.7.0
    - fire==0.7.0
    - grad-cam==1.5.4
    - kornia==0.8.0
    - lightning==2.5.0.post0
    - memory-profiler==0.61.0
    - scikit-image==0.25.2
    - timm==1.0.14
    - torch==2.6.0+cu118
    - torchvision==0.21.0+cu118
    - transformers==4.49.0
    - wandb==0.19.7
    - wildlife-datasets==1.0.5
    - wildlife-tools==1.0.1
    - zennit==0.5.1
